name: Build and deploy Node.js app to Azure Web App - pa4-27100307

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: 'Install Dependencies and Build'
        run: |
          cd webapp
          npm install
          npm run build --if-present

      - name: 'Upload Artifact for Deployment'
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: webapp/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'pa4-27100307'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_2C52DD7377504E8E97DA323322A9F197 }}
